#!/bin/bash
# Script de actualización manual simplificado

echo "=========================================="
echo "Actualización Manual - Radio UPEC"
echo "=========================================="
echo ""
echo "Este script te guiará paso a paso"
echo ""

# Primera Raspberry Pi
echo "📡 DISPOSITIVO 1: raspberry@172.20.248.102"
echo ""
echo "Paso 1: Conectarse y encontrar el archivo"
echo "Ejecuta estos comandos UNO POR UNO:"
echo ""
echo "ssh raspberry@172.20.248.102"
echo "pwd"
echo "ls -la"
echo "find ~ -name 'client.py' 2>/dev/null"
echo "systemctl status radio-client | grep 'Loaded:'"
echo ""
echo "Copia la ruta donde está client.py y pégala aquí:"
read -p "Ruta completa del directorio (ej: /home/raspberry): " DIR1

echo ""
echo "Paso 2: Copiar el archivo actualizado"
echo "Ejecuta este comando:"
echo ""
echo "scp client.py raspberry@172.20.248.102:$DIR1/"
echo ""
read -p "Presiona ENTER cuando hayas copiado el archivo..."

echo ""
echo "Paso 3: Reiniciar el servicio"
echo "Ejecuta:"
echo ""
echo "ssh raspberry@172.20.248.102 'sudo systemctl restart radio-client'"
echo ""
read -p "Presiona ENTER cuando hayas reiniciado el servicio..."

echo ""
echo "✅ Dispositivo 1 completado"
echo ""
echo "=========================================="
echo ""

# Segunda Raspberry Pi
echo "📡 DISPOSITIVO 2: raspberry2@172.20.228.207"
echo ""
echo "Paso 1: Conectarse y encontrar el archivo"
echo "Ejecuta estos comandos UNO POR UNO:"
echo ""
echo "ssh raspberry2@172.20.228.207"
echo "pwd"
echo "ls -la"
echo "find ~ -name 'client.py' 2>/dev/null"
echo "systemctl status radio-client | grep 'Loaded:'"
echo ""
echo "Copia la ruta donde está client.py y pégala aquí:"
read -p "Ruta completa del directorio (ej: /home/raspberry2): " DIR2

echo ""
echo "Paso 2: Copiar el archivo actualizado"
echo "Ejecuta este comando:"
echo ""
echo "scp client.py raspberry2@172.20.228.207:$DIR2/"
echo ""
read -p "Presiona ENTER cuando hayas copiado el archivo..."

echo ""
echo "Paso 3: Reiniciar el servicio"
echo "Ejecuta:"
echo ""
echo "ssh raspberry2@172.20.228.207 'sudo systemctl restart radio-client'"
echo ""
read -p "Presiona ENTER cuando hayas reiniciado el servicio..."

echo ""
echo "=========================================="
echo "✅ ¡ACTUALIZACIÓN COMPLETADA!"
echo "=========================================="
echo ""
echo "Verifica en el panel admin: http://localhost:3000"
echo "Deberías ver ahora el usuario correcto en cada dispositivo"
echo ""
